# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  fabric_net:
    name: fabric_net

services:
  couchdb0:
    container_name: couchdb0
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "1100:5984"

  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "1200:5984"

  peer1.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    depends_on:
      - couchdb1

  couchdb2:
    container_name: couchdb2
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "1300:5984"

  peer2.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    depends_on:
      - couchdb2

  couchdb3:
    container_name: couchdb3
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "1400:5984"

  peer3.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    depends_on:
      - couchdb3

  couchdb4:
    container_name: couchdb4
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "2100:5984"

  peer0.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
    depends_on:
      - couchdb4

  couchdb5:
    container_name: couchdb5
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "2200:5984"

  peer1.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
    depends_on:
      - couchdb5

  couchdb6:
    container_name: couchdb6
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "2300:5984"

  peer2.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
    depends_on:
      - couchdb6

  couchdb7:
    container_name: couchdb7
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "2400:5984"

  peer3.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:5984
    depends_on:
      - couchdb7

  couchdb8:
    container_name: couchdb8
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "3100:5984"

  peer0.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb8:5984
    depends_on:
      - couchdb8

  couchdb9:
    container_name: couchdb9
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "3200:5984"

  peer1.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb9:5984
    depends_on:
      - couchdb9

  couchdb10:
    container_name: couchdb10
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "3300:5984"

  peer2.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
    depends_on:
      - couchdb10

  couchdb11:
    container_name: couchdb11
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "3400:5984"

  peer3.org3.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
    depends_on:
      - couchdb11

  couchdb12:
    container_name: couchdb12
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "4100:5984"

  peer0.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
    depends_on:
      - couchdb12

  couchdb13:
    container_name: couchdb13
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "4200:5984"

  peer1.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb13:5984
    depends_on:
      - couchdb13

  couchdb14:
    container_name: couchdb14
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "4300:5984"

  peer2.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb14:5984
    depends_on:
      - couchdb14

  couchdb15:
    container_name: couchdb15
    extends:
      file: docker-service-extend.yaml
      service: couchdb-extend
    ports:
      - "4400:5984"

  peer3.org4.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb15:5984
    depends_on:
      - couchdb15
